# Generated by Django 3.0.6 on 2020-06-06 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nb_match', models.IntegerField()),
                ('totale_points', models.IntegerField()),
                ('nb_victoir', models.IntegerField()),
                ('nb_defait', models.IntegerField()),
                ('nb_match_null', models.IntegerField()),
                ('but_marque', models.IntegerField()),
                ('but_concede', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GroupOfTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('teams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Team')),
            ],
        ),
    ]
