# Generated by Django 3.0.6 on 2020-06-06 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupofteams',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
